version: '3.8'

services:
  # --- BACKEND SERVICE ---
  backend:
    build: ./Server        # Path to your backend folder
    ports:
      - "5000:5000"         # [Host Port] : [Container Port]
    environment:
      - PORT=5000
    volumes:
      - ./Server:/Server
      - /Server/node_modules
    networks:
      - man
    restart: always

  # --- FRONTEND SERVICE (VITE) ---
  frontend:
    build: ./Client       # Path to your frontend folder
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:5000 # Notice we use 'backend' not 'localhost'
    volumes:
      - ./Client:/Client
      - /Client/node_modules
    depends_on:
      - backend
    networks:
      - man
    restart: always
 

networks:
  man:
    driver: bridge
    

